### ISSUE TITLE
EmojiPicker.js problem

### ISSUE THREAD

**Issue by Ravaniss** [RobertMenke/rm-emoji-picker#14]
Hi,

I have a problem with this : C:\path\project\node_modules\rm-emoji-picker\dist\EmojiPicker.js:1

![capture](https://cloud.githubusercontent.com/assets/16159090/25774380/bc2ea31e-328d-11e7-94a2-06a8991d88d8.PNG)

so that crash my app... Am i missing somehing ? I said that because they have no issue about this.

Can you help about that please ?

ES6 is obligatory ?

Thanks.

**Comment by RobertMenke** [comment]
Hey @Ravaniss I'm not certain I fully understand the question, but I can go over a few basic requirements to use the library.

1) jQuery is a peer-dependency, meaning that you must have jQuery installed as a node-module through npm.
2) rm-emoji-picker, or more specifically EmojiPicker.js is a UMD module. Any build systems like webpack or rollup can understand the process of importing EmojiPicker
3) navigator is an object exposed by web browser runtimes that allow you to look at things like user agents, locations, etc. I'm using this to determine if the browser is mobile. 

Are you using this library in a web browser?

**Comment by Ravaniss** [comment]
Hello,

I have included jquery and es6. The error has gone.

Sorry for the inconvenience...
