### ISSUE TITLE
render from symbol/text to emoji

### ISSUE THREAD

**Issue by omaijdot** [RobertMenke/rm-emoji-picker#16]
Hi Robert,

Is there any possibility to call function in EmojiPicker object with React to render out from symbol/text to emoji? or is there any function to use EmojiPicker mapping to the sheet in React? 

because i using textarea as editor and saving symbol/text in my DB but when display i want to render it to emoji?

Thank you

**Comment by cyorobert** [comment]
Hey @omaijdot you're looking for the render method.

```
EmojiPicker.render("I am :smiling:")
```

**Comment by RobertMenke** [comment]
Hey @omaijdot you're looking for the render method.

```
EmojiPicker.render("I am :smiling:")
```

**Comment by omaijdot** [comment]
thank you.. it works.

**Comment by RobertMenke** [comment]
#17
