### ISSUE TITLE
Range error on IE11

### ISSUE THREAD

**Issue by simonhildebrandt** [RobertMenke/rm-emoji-picker#18]
Thanks heaps for a great tool - my teammates were pretty impressed with how quickly I got our app up and running with it. :)

Testing on IE11 though, I'm pretty sure I've run across this:
https://stackoverflow.com/questions/22914075/javascript-error-800a025e-using-range-selector

...in the `selectElement` method. 

Any awareness of this issue? (I'm planning to try and carve out a solution and PR it.)

**Comment by RobertMenke** [comment]
@simonhildebrandt Thanks for the kind words! I can definitely add some build instructions to the wiki. My webpack config is really messy right now since I used the same file for my example and UMD build. Unfortunately, I'm seeing this as I'm running off to work, but I can spend a few minutes at lunch today adding instruction.

**Comment by RobertMenke** [comment]
@simonhildebrandt Can you be more specific about what happens in IE11 related to the `selectElement` method?

**Comment by simonhildebrandt** [comment]
Yep - I'll try to extract some kind of stack trace from IE11.

**Comment by RobertMenke** [comment]
Awesome ty sir!

**Comment by simonhildebrandt** [comment]
The problem is that IE11 marks textareas as contenteditable by default, despite that not making any sense.
...and if I mark them explicitly with `contenteditable="false"` - well, it technically fixes the problem, but it also disables pasting into the field!

So, it seems like the correct behaviour is change the code that sets `_is_content_editable` to exclude textareas (and maybe inputs too?)

**Comment by RobertMenke** [comment]
@simonhildebrandt Interesting, so we essentially need a function akin to 

```javascript
function isContentEditable (element) {
     const tag = element.tagName.toLowerCase()
 
     return element.isContentEditable && tag !== "input" && tag !== "textarea"
}
```

I was not aware of that aspect of IE11, thank you for bringing that up. I'm hoping to have some time tomorrow morning to put a PR together.

**Comment by simonhildebrandt** [comment]
Yep, that's almost exactly what I came up with. :)

**Comment by RobertMenke** [comment]
@simonhildebrandt If #21 fixes this please mark this issue as closed. Thank you :).

**Comment by simonhildebrandt** [comment]
Yup. :)
