### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by simonhildebrandt** [RobertMenke/rm-emoji-picker#19]
While working on #18 I've had some trouble getting the tool to build.

After a few misfires I ran webpack and got a build - but it doesn't seem to have images in it.

Could we get some notes on the actual build process? (Happy to PR changes to the readme, if someone can point me in the right direction. :D )

**Comment by RobertMenke** [comment]
Hey @simonhildebrandt I just got home from work and was able to add a brief wiki. You can find my description of the build process here https://github.com/RobertMenke/rm-emoji-picker/wiki/Build-Instructions.

This is a rough draft, so please reach out on this issue thread if you still have questions. I'll leave it open for now. Thanks! #20

**Comment by simonhildebrandt** [comment]
Wicked, thanks @RobertMenke - I'll take a look in a few hours.

**Comment by simonhildebrandt** [comment]
Those instructions work great - I can build and debug in Chrome now. Two small things - `glob` seems to be missing as a dev dependency, and so does `emoji-js` (now that it's no longer sitting in `non_npm_dependencies`.) But using the current version of `emoji-js`, the picker now renders weirdly in IE11 (see pic.) I'll try reverting to the version of `emoji-js` that was previously inside the picker repo.
![screen shot 2017-06-26 at 2 01 27 pm](https://user-images.githubusercontent.com/279820/27524406-01808a88-5a78-11e7-90bf-e5df168d9f97.png)

**Comment by simonhildebrandt** [comment]
Ah, the image glitch was due to me using the wrong sheet - that much is fixed now. Still debugging the actually pasting logic though.

**Comment by RobertMenke** [comment]
Hmm I'll have to take a look at the current version. The version I pulled in for this project couldn't be installed via npm. I'm definitely interested in staying current.

The pasting logic can be somewhat tricky, especially when dealing with contenteditable stuff. I borrowed a lot of `Selection` and `Range` knowledge from a really bright guy on stackoverflow named Tim Down. https://github.com/timdown 

Let me know if I can be of help on any specific debugging task.

**Comment by Derekjohnson277** [comment]
@simonhildebrandt what is the correct sheet? My picker is rendering the same way. I'm using the sheets included with the package.

**Comment by simonhildebrandt** [comment]
@Derekjohnson277 - try updating to the latest version (0.3.10). Then if you still have trouble maybe try mirroring my config:

package.json:
```
    "emoji-datasource-apple": "^3.0.0",
```

emoji config:
```
    @emojiPicker = new App.Emoji.EmojiPicker
      use_sheets : true,
      sheets:
        apple:    App.asset("/images/emoji/apple/sheets-128/64.png")
```

(That emoji sheet is pulled from the package listed above.)

**Comment by RobertMenke** [comment]
@Derekjohnson277 Did that resolve your issue? If not, can you please post your code so we can take a look? Thanks!

**Comment by Derekjohnson277** [comment]
@RobertMenke I ended up going with a different emoji picker, but thanks!
