### ISSUE TITLE
Remove all content

### ISSUE THREAD

**Issue by Antoniobk** [RobertMenke/rm-emoji-picker#23]
How can I remove all content within div.contenteditable?
When I write and do line break and at the end I delete all the content stays one or two '<div><br></ div>'

**Comment by RobertMenke** [comment]
This should do the trick

**Comment by Antoniobk** [comment]
When I select several emojis it is overwritten to the first one, how can I solve that?

**Comment by RobertMenke** [comment]
Can you be more specific? What do you mean?

**Comment by Antoniobk** [comment]
It did not work me correctly..
![img1](https://user-images.githubusercontent.com/4043311/28231535-ac71af34-68b1-11e7-8efe-1cc90a64df28.jpg)
![img2](https://user-images.githubusercontent.com/4043311/28231561-c5940bb0-68b1-11e7-8040-cba913e5ad13.jpg)

**Comment by RobertMenke** [comment]
It absolutely does work. Open your console on this page and type:

```javascript
function removeContents(node) {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

removeContents(document.body)
```

the entire document body will be removed.

While we're at it, let's get a few things straight. This is not a content editable help forum. The issues section here is for help with the emoji picker library. Secondly, if you're going to request that I spend time helping you with your problem document your issue thoroughly with code. It's extremely disrespectful of you to waste my time with vaguely worded questions with no code and a poor follow up.

**Comment by Antoniobk** [comment]
Excuse me, I just wanted to solve a problem that I had when pressing ENTER wanted to send the content and then clean the area, but apparently it creates two div.
Sorry if I was impolite.
excuse my English

**Comment by RobertMenke** [comment]
My issue is not with the English, it's that you're requesting my time without putting any effort into opening an issue. I'm happy to help, but I don't appreciate when people request help without putting any effort into documenting their issue.
