### ISSUE TITLE
Consecutive Selection Of Emojis Overwrites Original Selection

### ISSUE THREAD

**Issue by Antoniobk** [RobertMenke/rm-emoji-picker#25]
When I select a several emojis consecutively in the div.contenteditable are not created consecutively but rather change the first emoji,

**Comment by RobertMenke** [comment]
I don't know what that means.

**Comment by Antoniobk** [comment]
When I select several emojis consecutively the first one is displayed and the others replace the first one, what I want to do is that they are shown followed not replacing the one that you select

**Comment by RobertMenke** [comment]
Oh I see what you're saying. This is a legitimate issue. I will leave this open and hopefully provide a fix very soon.

**Comment by marclindemann** [comment]
hi @RobertMenke you know when this will be fixxed?

**Comment by marclindemann** [comment]
@RobertMenke  i made a fix for it https://github.com/RobertMenke/rm-emoji-picker/pull/39
