### ISSUE TITLE
Wrong emoji offset

### ISSUE THREAD

**Issue by ogliznutsa** [RobertMenke/rm-emoji-picker#35]
Hi, it seems that there are problems with positioning of emojis (it's /examples/index.html on Windows 10): http://i.imgur.com/SbYceMY.png

**Comment by RobertMenke** [comment]
Yikes, looks like we may be suffering from an issue in Slack's emoji repo, which we're using for the images. https://github.com/iamcal/js-emoji

I'm honestly swamped with work through the rest of this week, but I'll do my best to provide an update this weekend. Thank you @ogliznutsa for bringing this to my attention.
