### ISSUE TITLE
rm-emoji-picker with Angular 2/4

### ISSUE THREAD

**Issue by anupam-git** [RobertMenke/rm-emoji-picker#38]
Hi,

Need some info on integrating with Angular 2/4 project.
Any information regarding this is appreciated.

Thanks.

**Comment by RobertMenke** [comment]
Hey @anupam-git can you show me what you have so far? Note that jQuery is a peer-dependency of this project. Once you provide the code you're using to initialize the picker I can be of more help.

**Comment by anupam-git** [comment]
Some complete examples would have helped.
