### ISSUE TITLE
❤️ Red Heart Emoji Results in Black Heart

### ISSUE THREAD

**Issue by vhmth** [RobertMenke/rm-emoji-picker#47]
Not sure if this is related to the lib itself, but it seems to work when using the native mac emoji picker. Video showcasing the issue (which itself is on the video page where you can test it with the comment input on the right):

https://www.useloom.com/share/e97afb9bf67a4e228c3244ab9e23582b

**Comment by cyorobert** [comment]
Hey @vhmth that typically is related to the font-family of your content-editable. Not all fonts support all emojis. I'm working on a branch that will allow you to force the emojis to be pasted into the editor as images, but for now mac computers will render the native unicode characters. I would try some different fonts. 

I actually just confirmed in a repo where I use this library that I have the same bug there. Fortunately, the unicode code points are indeed correct and can be saved, stored, and displayed correctly in other contexts.

**Comment by RobertMenke** [comment]
@vhmth After some more digging this appears to be a mac osx bug in general. If you look at a preview of a message in the Messages app that contains a red heart it appears exactly the same way that it appears in the video you linked in your issue.

**Comment by vhmth** [comment]
Huh very strange. Good ctch @RobertMenke!
