### ISSUE TITLE
[windows] picker.getText() returns an HTML instead of unicode

### ISSUE THREAD

**Issue by andremw** [RobertMenke/rm-emoji-picker#50]
I'm having some trouble to make it work on Windows because getText - which I use to save the unicode into the database - returns an HTML on Windows (using props _use_sheets_ and _sheets_).

I have no problems with it on Mac, using both textarea/div[contenteditable="true"].

<img width="638" alt="screen shot 2018-01-31 at 14 05 30" src="https://user-images.githubusercontent.com/878746/35633241-e178b570-068f-11e8-9317-53fe0bdfd5d6.png">

<img width="300" alt="screen shot 2018-01-31 at 14 05 39" src="https://user-images.githubusercontent.com/878746/35633249-e560ee46-068f-11e8-9a4b-b0925702f5ab.png">

**Comment by andremw** [comment]
I found out that I was passing a wrong element id as the input.

**Comment by jpablom** [comment]
Hi i have a similar problem. On windows too, but in my case this occurs on render method.
```js
//init emoji picker
const picker = new EmojiPicker({
    show_icon_tooltips: false,
    use_sheets: true,
    sheets: {
        apple: 'images/emojis/sheet_apple_64_indexed_128.png'
    }
});
picker.listenOn(icon, container, input);

//oninput event
let text = EmojiPicker.render(val);

/* on windows:
text = <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(images/emojis/sheet_apple_64_indexed_128.png; background-position: 45.833333333333336% 77.08333333333334%; background-size: 4900%)" data-codepoints="1f604"></span></span>
*/

// on mac render the emoji as expected
```

@RobertMenke any idea of how resolve this?
Thanks in advance
