### ISSUE TITLE
Inline sourceMappingURL on the dist file.

### ISSUE THREAD

**Issue by rsusanto** [RobertMenke/rm-emoji-picker#55]
I found out that the source map is included on the dist file. Importing this library, as suggested on the readme, will result it huge bundle file. Could we have it removed?

![screen shot 2018-09-03 at 14 53 01](https://user-images.githubusercontent.com/270331/44974188-1905f000-af89-11e8-828a-8a724ffa5431.png)

**Comment by RobertMenke** [comment]
@rsusanto Hey, great catch! This PR addresses the issue #56.
