### ISSUE TITLE
font-family: initial !important

### ISSUE THREAD

**Issue by saintpete** [RobertMenke/rm-emoji-picker#8]
Setting `font-family: initial !important` overrides the user's font setting and defaults to the browser's serifed font. The use of serif and sans-serif fonts in the same picker does not look as clean.

The font-family should be set to the same face and size as the word "Search" to appear consistent with the rest of the picker, and not use `!important` so that the application's stylesheet could override the default setting.

**Comment by saintpete** [comment]
@RobertMenke if certain fonts don't support emoji, this would still probably achieve the correct result: `font-family: sans-serif,inital`

**Comment by RobertMenke** [comment]
This has been removed from the styling, thanks for pointing that out.
